### ISSUE TITLE
refactor ssm_sv_init

### ISSUE THREAD

**Issue by Rewbert** [ssm-lang/ssm-runtime#21]
A question for @j-hui!

The initial code-generation scheme that I pilfered from the FDL-paper took a program like this:
```
f() {
  int x = var 5;
}
```
and turned that into
```c
// a struct

// an enter-function

// a step-function
```
with the _initialization_ of `x` happening inside the step-function.
```c
void step() {
  switch pc {
    case 0:
      initialize_int32(&x);
      assign_int32(&x, 5);
      // etc...
  }
}
```
A problem with this is that if the initialization only happens in a conditional branch, it might be skipped altogether and then the reference might skip initialization, making any usage of it illegal. The only use we might have made of it, however, was to dequeue any outstanding event on it before we exit the step-function.
The solution was naturally to lift the `initialize_int32` call to the _enter_-function, and leave the assignment of the initial value in the step-function.

With the new scheme in the `dev` branch, I am not sure that this is possible (or I am just missing it). `ssm_sv_init` takes as a parameter, not just the reference in question, but also the initial value of the reference. This value depends on when in time the reference is initialized, and can not be lifted to the enter-function without changing the semantics. If `ssm_sv_init` was split up into something like `ssm_sv_init(ssm_sv_t *sv)` and `ssm_sv_init_assign(ssm_sv_t *sv, ssm_value_t init_val)`, with `ssm_sv_init_assign` essentially behaving like `ssm_assign` with the exception that it doesn't mark the value as having been updated at this point in time, we can do the same refactoring.

Of course, if we never need to chase a reference if we don't initialize it this isn't an issue, but we seem to be dropping all of them before exiting the step-function.

**Comment by Rewbert** [comment]
```c
#define ssm_sv_init(sv, val)                                                   \
  do {                                                                         \
    ssm_to_sv(sv)->later_time = SSM_NEVER;                                     \
    ssm_to_sv(sv)->last_updated = SSM_NEVER;                                   \
    ssm_to_sv(sv)->triggers = NULL;                                            \
    ssm_to_sv(sv)->value = val;                                                \
  } while (0)
```
would become
```c
#define ssm_sv_init(sv)                                                        \
  do {                                                                         \
    ssm_to_sv(sv)->later_time = SSM_NEVER;                                     \
    ssm_to_sv(sv)->last_updated = SSM_NEVER;                                   \
    ssm_to_sv(sv)->triggers = NULL;                                            \
  } while (0)

#define ssm_sv_init_assign(sv, val)                                            \
  do {                                                                         \
    ssm_to_sv(sv)->value = val;                                                \
  } while (0)
```

**Comment by j-hui** [comment]
As you said, we previously had to eagerly initialize the metadata of scheduled variables in the `enter` function because we wanted to unconditionally call the `unschedule` function before leaving. However, we should now no longer store scheduled variables in the stack; instead, these are supposed to be heap-allocated. Then we simply drop them when they go out of scope.

So something like:

```
f() {
  // before
  int x = var 5;
  // after
}
```

would look like:

```c
void step_f (ssm_act_t *act) {
  f_act_t  *cont = container_of(act, f_act_t, act);
  switch (act->pc) {
    // ...
    // before
    cont->x = ssm_new_sv(ssm_marshal(5));
    // after
    // x goes out of scope:
    ssm_drop(x);
  }
}
```

If allocation only happens in a conditional branch, e.g.,:

```
f() {
  // before
  if (c) {
    int x = var 5;
    // conditional body
  }
  // after
}
```

Then we drop as soon as we leave the scope of the conditional:

```c
void step_f (ssm_act_t *act) {
  f_act_t  *cont = container_of(act, f_act_t, act);
  switch (act->pc) {
    // ...
    // before
    if (ssm_unmarshal(cont->c)) {
      cont->x = ssm_new_sv(ssm_marshal(5));
      // conditional body
      // x goes out of scope:
      ssm_drop(x);
    }
    // after
  }
}
```

Note that my latest commit onto `dev` from #20 makes it such that we no longer need a separate `ssm_sv_init` macro; instead, we just have an `ssm_new_sv` function, whose argument is the initial value. This allocates and initializes the scheduled variable all at once.

If you _must_ allocate a scheduled variable with a garbage value, just use a dummy value:

```c
ssm_new_sv(ssm_marshal(0xbeefcafe))
```

**Comment by j-hui** [comment]
Also I forgot to note that `unschedule` is automatically being called by `drop`; the lifetime of references is not strictly tied to its scope
